CompileFlags:
  Add:
    - -ferror-limit=0
    - -Wno-unknown-warning-option
    - --target=arm-none-eabihf
  Remove:
    # ARM GCC flags unsupported by clang
    - -mfp16-format=*
    - -mno-unaligned-access
    - -fno-allow-store-data-races
    - -fconserve-stack
    - --specs=*
    - -fstack-usage
    # ST-specific clang flags
    - --multi-lib-config=*
    - --driver-mode=*

Diagnostics:
  UnusedIncludes: Strict
  Suppress:
    - "pp_file_not_found"
