#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh"

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="JetBrainsMono Nerd Font"
# SPACE_CLICK_SCRIPT

PADDINGS=2

POPUP_BORDER_WIDTH=1
POPUP_CORNER_RADIUS=10

SHADOW=on

sketchybar  --bar   height=50 \
                    color=$BAR_COLOR \
                    shadow=$SHADOW \
                    position=right \
                    sticky=on \
                    padding_right=18 \
                    padding_left=18 \
                    corner_radius=10 \
                    y_offset=10 \
                    margin=10 \
                    blur_radius=20 \
          --default updates=when_shown \
                    icon.font="$FONT:Bold:14.0" \
                    icon.color=$ICON_COLOR \
                    icon.padding_left=$PADDINGS \
                    icon.padding_right=$PADDINGS \
                    label.font="$FONT:Bold:13.0" \
                    label.color=$LABEL_COLOR \
                    label.padding_left=$PADDINGS \
                    label.padding_right=$PADDINGS \
                    background.padding_left=$PADDINGS \
                    background.padding_right=$PADDINGS \
                    popup.background.border_width=2 \
                    popup.background.corner_radius=10 \
                    popup.background.border_color=$POPUP_BORDER_COLOR \
                    popup.background.color=$POPUP_BACKGROUND_COLOR \
                    popup.background.shadow.drawing=$SHADOW

# We add the items here
source "$ITEM_DIR/aerospace.sh"


sketchybar --update

